### ISSUE TITLE
ASAN error

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lv_lib_split_jpg#12]
I've started to update this repo to LVGL v8 but got Address sanitizer error:
```c
==9072==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55d071d02366 at pc 0x7f3ba84b5733 bp 0x7ffd438a5a00 sp 0x7ffd438a51a8
READ of size 512 at 0x55d071d02366 thread T0
    #0 0x7f3ba84b5732  (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x79732)
    #1 0x55d071ab240d in input_func ../lv_lib_split_jpg/lv_sjpg.c:289
    #2 0x55d071ab6faa in huffext ../lv_lib_split_jpg/tjpgd.c:315
    #3 0x55d071ab9838 in mcu_load ../lv_lib_split_jpg/tjpgd.c:515
    #4 0x55d071abe696 in jd_decomp ../lv_lib_split_jpg/tjpgd.c:952
    #5 0x55d071ab4f62 in decoder_read_line ../lv_lib_split_jpg/lv_sjpg.c:725
    #6 0x55d071a38549 in lv_img_decoder_read_line ../lvgl/src/draw/lv_img_decoder.c:164
    #7 0x55d0719f800f in lv_img_draw_core ../lvgl/src/draw/lv_draw_img.c:306
    #8 0x55d0719f6f74 in lv_draw_img ../lvgl/src/draw/lv_draw_img.c:84
    #9 0x55d07190b8ba in draw_img ../lvgl/src/widgets/lv_img.c:628
    #10 0x55d07190974a in lv_img_event ../lvgl/src/widgets/lv_img.c:485
    #11 0x55d071a402b9 in lv_obj_event_base ../lvgl/src/core/lv_event.c:96
    #12 0x55d071a438ab in event_send_core ../lvgl/src/core/lv_event.c:368
    #13 0x55d071a3ff2e in lv_event_send ../lvgl/src/core/lv_event.c:73
    #14 0x55d071a91553 in lv_refr_obj ../lvgl/src/core/lv_refr.c:681
    #15 0x55d071a91782 in lv_refr_obj ../lvgl/src/core/lv_refr.c:717
    #16 0x55d071a91161 in lv_refr_obj_and_children ../lvgl/src/core/lv_refr.c:618
    #17 0x55d071a90c82 in lv_refr_area_part ../lvgl/src/core/lv_refr.c:551
    #18 0x55d071a8fe0a in lv_refr_area ../lvgl/src/core/lv_refr.c:466
    #19 0x55d071a8edc8 in lv_refr_areas ../lvgl/src/core/lv_refr.c:389
    #20 0x55d071a8d750 in _lv_disp_refr_timer ../lvgl/src/core/lv_refr.c:216
    #21 0x55d071968fd4 in lv_timer_exec ../lvgl/src/misc/lv_timer.c:306
    #22 0x55d0719682af in lv_timer_handler ../lvgl/src/misc/lv_timer.c:97
    #23 0x55d071af87c0 in main ../main.c:141
    #24 0x7f3ba6d6cbf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)
    #25 0x55d0718cc349 in _start (/home/kisvegabor/projects/littlevgl/eclipse-workspace/lv_sim_eclipse_sdl_v8.0/Debug/lv_sim_eclipse_sdl_v8.0+0x21b349)

0x55d071d02366 is located 0 bytes to the right of global variable 'wallpaper_jpg_map' defined in '../lv_lib_split_jpg/example/images/wallpaper_jpg.c:12:69' (0x55d071ced800) of size 84838
SUMMARY: AddressSanitizer: global-buffer-overflow (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x79732) 
Shadow bytes around the buggy address:
  0x0aba8e398410: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aba8e398420: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aba8e398430: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aba8e398440: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aba8e398450: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0aba8e398460: 00 00 00 00 00 00 00 00 00 00 00 00[06]f9 f9 f9
  0x0aba8e398470: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aba8e398480: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aba8e398490: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aba8e3984a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aba8e3984b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==9072==ABORTING
```

To reproduce:
```c
  lv_split_jpeg_init();
  LV_IMG_DECLARE( wallpaper_jpg );

  lv_obj_t * img1 = lv_img_create(lv_scr_act());
  lv_img_set_src( img1,  &wallpaper_jpg);
```

@vinodstanur could you take a look at it?

**Comment by vinodstanur** [comment]
Okay, I will check.

**Comment by cmumford** [comment]
@kisvegabor I fuzzed TJpgDec a while back and found that it doesn't do a great job of validating input. I fixed several errors in my fork of the project which is at https://github.com/cmumford/TJpgDec. You should be able to copy tjpgdec.c from https://github.com/cmumford/TJpgDec/commit/1fc035d2e34c50589ef33e51c192ba15679b50e6 to see if your crash goes away.

**Comment by kisvegabor** [comment]
@cmumford 
The issue still persists :slightly_frowning_face: 
I haven't fully understood the issue yet, but I think the problem is that the library always tries to read 512 bytes of data but when the last chunk is read the jpeg data can be read out of bounds (if its size if is not Nx512).

**Comment by cmumford** [comment]
Thx @kisvegabor Is this image available so that I can try to reproduce?

**Comment by kisvegabor** [comment]
Sure, I've used [this image](https://github.com/lvgl/lv_lib_split_jpg/blob/master/example/images/wallpaper_jpg.c) from the example folder. Copy pasting the code snippet from my first comment should work out of the box.

**Comment by cmumford** [comment]
@kisvegabor I think that wallpaper_jpg is OK - at least for TJpgDec. I hacked my fuzzer to only fuzz that image data, and it produced no errors on Ubuntu. My branch is at https://github.com/cmumford/TJpgDec/tree/wallpaper-test. I believe there is a bug in lv_lib_split_jpg's `input_func` in lv_sjpg.c on [line 291](https://github.com/lvgl/lv_lib_split_jpg/blob/71627cde583dbea83bc1deb5ea9f8559d65b89bd/lv_sjpg.c#L291). TJpgDec calls [infunc](https://github.com/cmumford/TJpgDec/blob/ea663e4715d5712a50c84ddfcb851ba4063cb7f4/src/tjpgd.c#L267) with the number of bytes that it *wants* to read (or skip), but infunc needs to verify the request size and return the number of bytes read/skipped (very similar to fread). My fuzzer does this here:

https://github.com/cmumford/TJpgDec/blob/ea663e4715d5712a50c84ddfcb851ba4063cb7f4/test/fuzz/fuzzer.cc#L34-L37

**Comment by kisvegabor** [comment]
Thank you @cmumford. I've checked it, and I agree the issue could be there.

I've tried to add the read size validation but it's rather complex because of the custom JPEG handling of SJPG.

@vinodstanur do you have some time to check it?

**Comment by cmumford** [comment]
This should be addressed and not closed. I may give it a try if I have some time.

**Comment by cmumford** [comment]
I looked into this a bit, and I think the only real solution is to add a `src_len` parameter to `io_source_t` so that the buffer size can be known. Unfortunately this has far reaching consequences as **all** API's which pass a `src` parameter will need to have a new `src_len` parameter added. So, not a simple change.

I'm happy to do the work, but because so many API's will be changed I wanted to contact the project owners to see if this is a desired change. IMHO if we want LVGL to be able to display images from untrusted sources then this change is a must. @kisvegabor what do you think?

**Comment by kisvegabor** [comment]
I agree that this improvement is required. Thank you for offering your help!

Fortunately, the only public API is `lv_split_jpeg_init` so we are free to add any parameters to the internal functions.

**Comment by cmumford** [comment]
@kisvegabor I just uploaded a candidate fix at https://github.com/cmumford/lv_lib_split_jpg/tree/img-bug.  So far I've only compiled it - haven't run the example program, or anything else.  Are you in a position to give this a try?

**Comment by cmumford** [comment]
Made a few changes to initial upload. I did build and run the demo_jpg_sjpg example, but don't have a handy project for ASAN testing.
